# Generated by Django 3.1 on 2022-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('reply', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'class ContactMessage',
            },
        ),
    ]
